services:
  flask:
    build: .
    container_name: tg-check
    restart: on-failure

  nginx:
    image: nginx:alpine
    container_name: tg-check-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
